server:
  port: 3000
mysql:
  host: 192.168.121.134
  port: 3306
  database: tristan
  user: tristan
  password: tristan123
  charset: utf8mb4
work_wechat:
  app_id: ww144549834d4c265e
  agent_id: 1000006
